export const html = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Signal Harvester</title>
<style>
:root{color-scheme:dark;--bg:#07111f;--panel:rgba(15,23,42,.82);--line:rgba(148,163,184,.18);--text:#e5edf8;--muted:#94a3b8;--accent:#38bdf8;--good:#34d399;--bad:#fb7185;--warn:#fbbf24;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 10% 0,rgba(56,189,248,.26),transparent 34rem),radial-gradient(circle at 90% 10%,rgba(52,211,153,.16),transparent 28rem),linear-gradient(135deg,#07111f,#0f172a 55%,#111827);color:var(--text)}main{width:min(1180px,calc(100vw - 32px));margin:0 auto;padding:34px 0 48px}header{display:flex;justify-content:space-between;align-items:flex-start;gap:18px;margin-bottom:22px}h1{font-size:clamp(34px,5vw,58px);line-height:.95;letter-spacing:-.06em;margin:0}.sub{color:var(--muted);line-height:1.55;max-width:720px;margin-top:12px}.pill{border:1px solid var(--line);background:rgba(15,23,42,.64);border-radius:999px;padding:10px 14px;color:var(--muted);white-space:nowrap}.grid{display:grid;gap:16px}.cards{grid-template-columns:repeat(4,minmax(0,1fr));margin-bottom:16px}.card,.panel{border:1px solid var(--line);background:var(--panel);backdrop-filter:blur(18px);border-radius:24px;box-shadow:0 24px 80px rgba(0,0,0,.35)}.card{padding:20px}.label{font-size:12px;text-transform:uppercase;letter-spacing:.07em;color:var(--muted)}.value{font-size:34px;font-weight:780;letter-spacing:-.04em;margin-top:10px}.hint{font-size:13px;color:var(--muted);margin-top:6px}.layout{grid-template-columns:1fr 1fr;align-items:start}.panel{padding:20px}.head{display:flex;justify-content:space-between;gap:14px;align-items:center;margin-bottom:14px}h2{font-size:18px;margin:0}.small{font-size:13px;color:var(--muted)}button,input,select{font:inherit;border-radius:12px;border:1px solid var(--line);background:rgba(2,6,23,.42);color:var(--text);padding:10px 12px}button{cursor:pointer;background:linear-gradient(135deg,rgba(14,165,233,.9),rgba(16,185,129,.82));border:0;font-weight:750}table{width:100%;border-collapse:collapse}th{text-align:left;color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.06em;padding:10px;border-bottom:1px solid var(--line)}td{padding:12px 10px;border-bottom:1px solid rgba(148,163,184,.1);font-size:14px;vertical-align:top}.tag{display:inline-flex;border:1px solid rgba(56,189,248,.3);background:rgba(14,165,233,.12);color:#bae6fd;border-radius:999px;padding:4px 9px;font-size:12px;font-weight:700}.doc{display:grid;gap:8px;padding:14px;border:1px solid rgba(148,163,184,.12);background:rgba(2,6,23,.28);border-radius:16px;margin-bottom:10px}.doc a{color:#bae6fd;text-decoration:none}.pos{color:var(--good)}.neg{color:var(--bad)}.neu{color:var(--muted)}@media(max-width:900px){.cards,.layout{grid-template-columns:1fr}header{flex-direction:column}}</style>
</head>
<body><main>
<header><div><h1>Signal<br/>Harvester</h1><div class="sub">Reusable collection jobs for news, market and sentiment datasets. This first slice collects BTC news, scores it, stores it over time, and exposes it to trading systems.</div></div><div class="pill" id="status">Loading…</div></header>
<section class="grid cards"><div class="card"><div class="label">Documents</div><div class="value" id="docs">—</div><div class="hint">Stored news records</div></div><div class="card"><div class="label">24h score</div><div class="value" id="score">—</div><div class="hint">BTC sentiment</div></div><div class="card"><div class="label">Positive</div><div class="value pos" id="positive">—</div><div class="hint">24h articles</div></div><div class="card"><div class="label">Negative</div><div class="value neg" id="negative">—</div><div class="hint">24h articles</div></div></section>
<section class="grid layout"><div class="panel"><div class="head"><h2>Collection jobs</h2><button onclick="runBtc()">Run BTC news now</button></div><table><thead><tr><th>Name</th><th>Topic</th><th>Status</th><th>Last run</th></tr></thead><tbody id="jobs"></tbody></table><div class="head" style="margin-top:22px"><h2>Create RSS job</h2></div><div class="grid" style="grid-template-columns:1fr 1fr"><input id="name" placeholder="Job name"/><input id="topic" placeholder="Topic e.g. ETH"/><input id="feed" style="grid-column:1/-1" placeholder="RSS feed URL"/><button onclick="createJob()" style="grid-column:1/-1">Create job</button></div></div><div class="panel"><div class="head"><h2>Latest BTC news</h2><span class="small">auto-refreshes</span></div><div id="documents"></div></div></section>
</main><script>
const fmt=new Intl.NumberFormat();
function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function dt(v){return v?new Date(v).toLocaleString(undefined,{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}
async function refresh(){try{const [jobs,docs,summary]=await Promise.all([fetch('/api/jobs').then(r=>r.json()),fetch('/api/documents?topic=BTC&limit=30').then(r=>r.json()),fetch('/api/sentiment/summary?topic=BTC&windowHours=24').then(r=>r.json())]);document.getElementById('status').textContent='Live · '+new Date().toLocaleTimeString();document.getElementById('docs').textContent=fmt.format(docs.length);document.getElementById('score').textContent=Number(summary.average_score??0).toFixed(2);document.getElementById('positive').textContent=summary.positive??0;document.getElementById('negative').textContent=summary.negative??0;document.getElementById('jobs').innerHTML=jobs.map(j=>'<tr><td>'+esc(j.name)+'</td><td><span class="tag">'+esc(j.topic)+'</span></td><td>'+esc(j.status)+'</td><td>'+dt(j.lastRunAt)+'</td></tr>').join('');document.getElementById('documents').innerHTML=docs.map(d=>'<div class="doc"><div><span class="tag">'+esc(d.sentimentLabel)+'</span> <span class="small">'+esc(d.sourceName)+' · '+dt(d.publishedAt)+'</span></div><a href="'+esc(d.url)+'" target="_blank" rel="noreferrer">'+esc(d.title)+'</a><div class="small">score '+Number(d.sentimentScore).toFixed(2)+'</div></div>').join('')}catch(e){document.getElementById('status').textContent='Error · '+e.message}}
async function runBtc(){await fetch('/api/jobs/btc-news/run',{method:'POST'});setTimeout(refresh,1000)}
async function createJob(){const name=document.getElementById('name').value;const topic=document.getElementById('topic').value;const feed=document.getElementById('feed').value;await fetch('/api/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,topic,sourceKind:'news-rss',config:{feeds:[{name,url:feed}]}})});refresh()}
refresh();setInterval(refresh,10000);
</script></body></html>`;
